default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development
  url: <%= ENV['$SCALINGO_POSTGRESQL_URL'] %>


test:
  <<: *default
  database: rails-watch-list_test
